#!/bin/sh
if [ -a .commit ]
    then
    echo "REMOVE .commit"
    rm .commit
    git add $(git rev-parse --show-toplevel)/fme-calendar.js
    git add $(git rev-parse --show-toplevel)/spec/fme-calendar-spec.js
    git add $(git rev-parse --show-toplevel)/karma_tests.html
    git add $(git rev-parse --show-toplevel)/git-hooks/.
    git commit --amend -C HEAD --no-verify
fi
exit 0